### ISSUE TITLE
Xcode Server Bot is not producing a `.ipa` to upload to TestFlight

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#11]
In the directions for uploading to TestFlight, you say:

 > Now you need a post-integration trigger:
 > `PATH=/Library/Frameworks/Python.framework/Versions/3.4/bin:$PATH`
 > `cavejohnson xcodeGUITricks --new-ipa-path myapp.ipa`

Instead, for my project, I see the following files under `Derived Data > Build > Products`:

```
myApp.bundle
myApp.app
myApp.app.dSYM
myApp.a
```

The Scheme builds the library files above, etc., but also a demo app.

I'm not getting a `.ipa` however. Is there a way to force Xcode Server to build the .ipa? Am I looking for it in the wrong location? The scheme is in the Release configuration.

**Comment by drewcrawford** [comment]
Paste the output of `env` in your post-build trigger.

**Comment by pkamb** [comment]
`env`

output:

```
XCS=1
XCS_BOT_NAME=MC_Demo TestFlightBot
XCS_SOURCE_DIR=/Library/Developer/XcodeServer/Integrations/Caches/42693afa90cf4f8cd0b1240df90e50c1/Source
SHELL=/bin/false
XCS_WARNING_CHANGE=0
XCS_INTEGRATION_RESULT=succeeded
TMPDIR=/var/folders/kb/0k2rbxg92f9f0jgyzmcjxtnc000086/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.8TPjJLHnCO/Render
XCS_TEST_FAILURE_COUNT=0
XCS_BOT_TINY_ID=1783F77
XCS_INTEGRATION_ID=42693afa90cf4f8cd0b1240df951d24e
USER=_xcsbuildd
XCS_TEST_FAILURE_CHANGE=0
XCS_INTEGRATION_TINY_ID=CFD9B6E
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.o5PvntXuSi/Listeners
__CF_USER_TEXT_ENCODING=0x106:0x0:0x0
PATH=/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
XCS_BOT_ID=42693afa90cf4f8cd0b1240df90e50c1
PWD=/Library/Developer/XcodeServer/Integrations/Caches/42693afa90cf4f8cd0b1240df90e50c1/Source
XCS_XCODEBUILD_LOG=/Library/Developer/XcodeServer/Integrations/Integration-42693afa90cf4f8cd0b1240df951d24e/build.log
XPC_FLAGS=0x0
XCS_ERROR_COUNT=0
XCS_ANALYZER_WARNING_COUNT=0
XCS_TESTS_CHANGE=0
XPC_SERVICE_NAME=0
XCS_ERROR_CHANGE=0
SHLVL=1
HOME=/var/_xcsbuildd
XCS_ANALYZER_WARNING_CHANGE=0
LOGNAME=_xcsbuildd
XCS_WARNING_COUNT=0
XCS_TESTS_COUNT=0
XCS_OUTPUT_DIR=/Library/Developer/XcodeServer/Integrations/Integration-42693afa90cf4f8cd0b1240df951d24e
XCS_INTEGRATION_NUMBER=31
_=/usr/bin/env
```

**Comment by drewcrawford** [comment]
That is an odd output.

Is this bot configured to perform an archive?  Does the build log suggest the archive succeeded?

**Comment by pkamb** [comment]
Ah. The integration succeeds, but the build log shows the archive failure. I'll look into this.

![screen shot 2015-03-10 at 6 50 13 pm](https://cloud.githubusercontent.com/assets/342355/6588957/4a14efb2-c756-11e4-94dc-c3823d11f268.png)

 > Check dependencies
 > Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “team_XYZ” were found.
 > CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

 > 2015-03-10 18:47:19.129 xcodebuild[41331:3752531] [MT]  > IDEBuildOperationQueueSetResourceManagement: Resetting max operation count to 6
> ** ARCHIVE FAILED **

**Comment by pkamb** [comment]
Ok, I've got the Archive to complete by adding my certs and private keys to the build server's **System** keychain. Copied the provisioning profiles to the Server as well.

This adds `XCS_ARCHIVE` and `XCS_PRODUCT` to the env variables:  

`XCS_ARCHIVE=/Library/Developer/XcodeServer/Integrations/Integration-42693afa90cf4f8cd0b1240df9575770/Archive.xcarchive`

`XCS_PRODUCT=TestFlightBot.ipa`

![screen shot 2015-03-10 at 11 38 54 pm](https://cloud.githubusercontent.com/assets/342355/6591525/9fa32d54-c77e-11e4-862d-f79dd52514e7.png)

**Comment by pkamb** [comment]
Unfortunately that `${XCS_PRODUCT}` doesn't appear to work with `uploadiTunesConnect`.

`cavejohnson uploadiTunesConnect --itunes-app-id 12345678 --itunes-username me@me.com --itunes-password mypassword --ipa-path ${XCS_PRODUCT}`

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cavejohnson", line 9, in <module>
    load_entry_point('cavejohnson==1.0.1', 'console_scripts', 'cavejohnson')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 566, in main_func
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 117, in uploadITMS
    upload_itunesconnect(args.itunes_app_id, args.itunes_username, args.itunes_password, args.ipa_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 124, in upload_itunesconnect
    data = load_plist_ipa(ipa_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 315, in load_plist_ipa
    zip_file = zipfile.ZipFile(ipa_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py", line 923, in __init__
    self.fp = io.open(file, modeDict[mode])
FileNotFoundError: [Errno 2] No such file or directory: 'TestFlightBot.ipa'
After Integration Trigger: DONE
``

**Comment by pkamb** [comment]
This works: 

`cavejohnson uploadiTunesConnect --itunes-app-id 12345678 --itunes-username me@me.com --itunes-password mypassword --ipa-path ${XCS_OUTPUT_DIR}/${XCS_PRODUCT}`

**Comment by drewcrawford** [comment]
FYI, `--ipa-path` is optional.  Omitting it should do the right thing automatically.

The only reason you'd need to provide it is if you want to upload a different IPA than the one Xcode built.  For example, if you're running `xcodeGUITricks` or `reSignIPA`.

**Comment by pkamb** [comment]
:+1: 

`cavejohnson uploadiTunesConnect --itunes-app-id 12345678 --itunes-username me@me.com --itunes-password mypassword`
