### ISSUE TITLE
No such file or directory: `Archive.xcarchive/SwiftSupport`

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#12]
FYI, I'm seeing the below when I use `xcodeGUITricks`.

`cavejohnson xcodeGUITricks --new-ipa-path ${XCS_PRODUCT}`

Xcode Version 6.1.1 (6A2008a)

It looks like `xcodeGUITricks` is used to correct  the missing SwiftSupport folder, so it may not be necissary in my case. Thought you should know, in case the Xcode defaults have changed.

http://faq.sealedabstract.com/xcodeCI/#signing-for-distribution

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cavejohnson", line 9, in <module>
    load_entry_point('cavejohnson==1.0.1', 'console_scripts', 'cavejohnson')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 566, in main_func
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 81, in xcodeGUITricksArgs
    xcodeGUITricks(args.archive_path, args.new_ipa_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 101, in xcodeGUITricks
    shutil.copytree(archive_path + "/SwiftSupport", tempdir + "/SwiftSupport")
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shutil.py", line 296, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Developer/XcodeServer/Integrations/Integration-42693afa90cf4f8cd0b1240df964d41d/Archive.xcarchive/SwiftSupport'
```

**Comment by drewcrawford** [comment]
Does your app actually contain any Swift?

**Comment by pkamb** [comment]
No, it doesn't. The readme's example code just seems to indicate that using `xcodeGUITricks` is required, but I guess it's not if there's no Swift in the app?

**Comment by drewcrawford** [comment]
It's a good question.  I'm not entirely sure.

Currently that command

1.  Fixes the SwiftSupport (which you don't need in a pure ObjC app)
2.  Fixes symbols for iTunesConnect (which you may or may not need.  It's sort of academic at the moment because there's really no crash reports coming in from iTunesConnect.)

Potentially these 2 things could be separated into separate commands if it turns out you need only the second one.  That would probably be a good patch topic.  However I probably won't get to it any time soon since I'm not doing a lot of ObjC work.  I'd be happy to merge it though.
