### ISSUE TITLE
Errror while reSignIPA

### ISSUE THREAD

**Issue by adamszeptycki** [drewcrawford/CaveJohnson#4]
I tried to resign ipa and got following error:
```
/var/folders/y8/2htjmh5n7hl95kvbjpmr1yd0000086/T/tmpsbl7a9ze/Payload/Test.app: replacing existing signature
Traceback (most recent call last):
  File "/usr/bin/cavejohnson", line 9, in <module>
    load_entry_point('cavejohnson==1.0.1', 'console_scripts', 'cavejohnson')()
  File "/usr/local/lib/python3.4/site-packages/cavejohnson/__init__.py", line 518, in main_func
    args.func(args)
  File "/usr/local/lib/python3.4/site-packages/cavejohnson/__init__.py", line 117, in uploadITMS
    upload_itunesconnect(args.itunes_app_id, args.itunes_username, args.itunes_password, args.ipa_path)
  File "/usr/local/lib/python3.4/site-packages/cavejohnson/__init__.py", line 124, in upload_itunesconnect
    data = load_plist_ipa(ipa_path)
  File "/usr/local/lib/python3.4/site-packages/cavejohnson/__init__.py", line 283, in load_plist_ipa
    assert len(info_plists) == 1
AssertionError
 ```
Any idea how to fix this problem?

**Comment by drewcrawford** [comment]
Is it possible for you to email me an affected IPA?

It's caused by, essentially, an unexpected configuration of Info.plist files, so it's not sure where to get the app's data.  With a sample case I could produce something better.

**Comment by adamszeptycki** [comment]
Sadly I can't send IPA (it's not my own project).

I can send you Info.plist (I will change some crucial data).

**Comment by drewcrawford** [comment]
In that case I'll need a "cleanroom" test project.  This issue is caused by the configuration of the (multiple) Info.plists and their paths in the IPA.  It's not isolated to 1 plist.

That being the case however, it should be very straightforward to produce a test project that exhibits the issue.  It just needs to create plist files in the same locations, with roughly the same contents.  As long as it does that, you should get the same error, and I can work from that.

**Comment by drewcrawford** [comment]
I'm clearing the milestone assignment, since no test case has been produced and I don't want to hold the release waiting indefinitely.
